vich_uploader:
    db_driver: orm

    mappings:
        avatars_user:
            uri_prefix: /uploads/avatars_user
            upload_destination: '%kernel.project_dir%/public/uploads/avatars_user'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        back_ground_avatars_user:    
            uri_prefix: /uploads/avatar_background_user
            upload_destination: '%kernel.project_dir%/public/uploads/avatar_background_user'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        back_ground_avatars_club:    
            uri_prefix: /uploads/avatar_background_club
            upload_destination: '%kernel.project_dir%/public/uploads/avatar_background_club'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        avatars_club:    
            uri_prefix: /uploads/avatars_club
            upload_destination: '%kernel.project_dir%/public/uploads/avatars_club'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        post_images:
            uri_prefix: /uploads/images_posts
            upload_destination: '%kernel.project_dir%/public/uploads/images_posts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer